# Generated by Django 3.1 on 2020-09-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for recipe', primary_key=True, serialize=False, unique=True)),
                ('recipe_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fulfillment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_price_start', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_price_end', models.DecimalField(decimal_places=2, max_digits=6)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ing_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for ingredient', primary_key=True, serialize=False, unique=True)),
                ('foreign_id', models.CharField(editable=False, max_length=50)),
                ('ing_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('metadata', models.JSONField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
