# Generated by Django 3.1 on 2020-09-08 16:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200908_1418'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('recipe_book', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
