# Generated by Django 3.1 on 2020-09-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200909_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fulfillment_date',
        ),
    ]
