# Generated by Django 3.1.2 on 2020-11-02 03:28

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_quantity', models.PositiveSmallIntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact_number', models.CharField(max_length=15, null=True)),
            ],
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
    ]
