# Generated by Django 3.1 on 2020-09-08 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0004_auto_20200908_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('gb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_order_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_order_quantity', models.PositiveIntegerField(blank=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('order_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('GROUPBUY_IN_PROGRESS', 'GROUPBUY_IN_PROGRESS'), ('GROUPBUY_EXPIRED', 'GROUPBUY_EXPIRED'), ('DELIVERY_IN_PROGRESS', 'DELIVERY_IN_PROGRESS'), ('DELIVERED', 'DELIVERED')], default='PENDING_APPROVAL', max_length=20)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
            ],
        ),
    ]
