# Generated by Django 3.1 on 2020-09-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbuy',
            name='status',
        ),
    ]
