# Generated by Django 3.1 on 2020-09-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200909_0202'),
        ('orders', '0002_remove_groupbuy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
    ]
