# Generated by Django 3.1 on 2020-09-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200909_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
