# Generated by Django 3.1 on 2020-09-09 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20200909_0338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupbuy',
            managers=[
                ('groupbuys', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_quantity', models.PositiveSmallIntegerField()),
                ('delivery_address', models.CharField(max_length=200)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
