# Generated by Django 3.1 on 2020-09-09 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200909_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='fulfillment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 6, 13, 57, 79076, tzinfo=utc)),
        ),
    ]
