# Generated by Django 3.1 on 2020-09-09 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200909_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='fulfillment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 16, 53, 56, 886722, tzinfo=utc)),
        ),
    ]
