# Generated by Django 3.1.2 on 2020-11-02 02:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20201102_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupbuy',
            fields=[
                ('gb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_order_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('order_by', models.DateTimeField()),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fulfillment_date', models.DateTimeField(default=datetime.datetime(2020, 11, 9, 2, 57, 59, 28585, tzinfo=utc))),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('groupbuys', django.db.models.manager.Manager()),
            ],
        ),
    ]
